eazytapes/eazytapes/urls.py
from django.contrib import admin
from django.urls import path

import web.views

urlpatterns = [
    path('', web.views.principal, name="Principal"),
    path('bar/<int:bar_id>', web.views.bar, name="Bar"),
    path('tapa/<int:pk>', web.views.TapaView.as_view(), name="Tapa"),
    path('admin/', admin.site.urls),
]

eazytapes/web/models.py
from django.db import models

# Create your models here. Base de dades; Controller - Python (logical business)
# Escrit en python pero el django ho tradueix a sql

class Bar(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return self.name
    

class Tapa(models.Model):
    name = models.CharField(max_length=200)
    bar = models.ForeignKey(Bar, on_delete=models.CASCADE) # Clau forana que apunta a bar, si es borra el bar tambe es borrara
    #la tapa

    def __str__(self) -> str:
        return self.name+" del "+self.bar.name
    

eazytapes/web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from web.models import Bar, Tapa
from django.views import generic

# Create your views here. Html de la aplicació

#def principal(request):
#    bars = Bar.objects.all()
#    resposta = [bar.name for bar in bars]
#    html = "<br />".join(resposta)
#    return HttpResponse(html)

def principal(request):
    bars = Bar.objects.all()
    return render(request, 'web/index.html', {"bars": bars})

def bar(request, bar_id):
    bar = Bar.objects.get(pk=bar_id) #primary key
    return render(request, 'web/bar.html', {"bar": bar})



class TapaView(generic.DetailView):
    model = Tapa
    template_name = 'web/tapa.html'

eazytapes/web/templates/web/bar.html
{{ bar.name }}

<ul>
    {% for tapa in bar.tapa_set.all %}
        <li><a href={% url "Tapa" tapa.id %}>{{ tapa.name}}</a></li>
    {% endfor %}
</ul>

eazytapes/web/templates/web/index.html
<h2>AdvisorTrip</h2>


<ul>
    {% for bar in bars %}
        <li><a href={% url 'Bar' bar.id %}> {{ bar.name }} </a></li>
    {% endfor %}
</ul>

eazytapes/web/templates/web/tapa.html
{{ tapa.name }} @ {{ tapa.bar.name}}